apiVersion: v1
kind: Pod
metadata:
  name: angular-app-pod
  labels:
    app: angular-nginx
    type: front-end
spec:
  containers:
    - name: simple-ng-app
      image: subhaationic3/simple-angular-app:latest
