apiVersion: v1
kind: Service
metadata:
  name: angular-app-service
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30004
  selector:
    app: angular-nginx
    type: front-end
